# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f35c9b457e3043f8e404a5f34b644a59db35084e13feb7d41740f5b195d0f733152b5bf80d46f51d9cf6da7b953a4ae7bd2cb47ac94d3f2dca7928dc53377a5e

test:
  secret_key_base: 5e4c4213533ff78bca3242a02f1fdb6ad919b5b1c96e56a04b8ec95bd091a3c9f3d0e1d30e2f50d357b7367943b7ed7d62548a0b344406717dcd718e665def6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
