source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.2'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'active_model_serializers', '~> 0.8.0'
gem 'rspec-rails', group: [:development, :test]
gem 'db-query-matchers', group: :test
gem 'haml-rails'
gem 'font-awesome-rails'
gem 'bootstrap-sass'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'json'


group :assets do
  gem 'therubyracer', platforms: :ruby
end

